---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: install git on ansible ubuntu nodes
    apt:
      name: git
      state: present

  - name: install git on ansible redhat node
    yum:
     name: git
     state: started    