---
- hosts: 172.31.35.15
  become: yes
  tasks: 
  - name:  install  webserver
    apt:
      name: apache2
      state: present

  - name: copy indexfile into ansible node
    template:
       src:  indexfile.j2
       dest: /var/www/html/index.html    